In [1]:
from gensim.models import Word2Vec

In [2]:
from urllib import request

In [7]:
import pandas as pd
import numpy as np

In [4]:
# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [6]:
# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [9]:
def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations

In [20]:
song_id = 74949
print(songs_df.iloc[song_id])
print_recommendations(song_id)

title     She's Not There
artist            Santana
Name: 74949 , dtype: object

                             title                     artist
id
10040          The Show Must Go On                 Pink Floyd
33322        San Franciscan Nights  Eric Burdon & The Animals
17741            Run With The Pack                Bad Company
28498                      Fantasy                  Aldo Nova
50990   After The Gold Rush (Live)   Neil Young & Crazy Horse

In [18]:
songs_df[songs_df['artist'] == 'Santana']

                                                 title   artist
id
2872                                         Evil Ways  Santana
3039                                 Black Magic Woman  Santana
3416                           Smooth (w\/ Rob Thomas)  Santana
3853                                 Why Don't You & I  Santana
4141                                           Winning  Santana
...                                                ...      ...
69107   Do You Like The Way (w\/ Lauryn Hill & Cee-Lo)  Santana
70837              Just Feel Better (w\/ Steven Tyler)  Santana
74948           Sunshine Of Your Love (w\/ Rob Thomas)  Santana
74949                                  She's Not There  Santana
74950                                   Well All Right  Santana

[61 rows x 2 columns]